### PR TITLE
Update dependency on ember-cli-head

### PR DESCRIPTION
**Pull request by cibernox**

### CODE REVIEW

**Comment by cibernox** [comment]
@simonihmig I didn't realiza that you did that too, but I guess that this supersedes it

**Comment by simonihmig** [comment]
@cibernox yeah, it is ok, thanks for stealing my PR! 😉

**Comment by ronco** [comment]
Thanks @cibernox & @simonihmig !  I've been hands off with this final push to FastBoot 1.0.  Is this good to go for npm release?

**Comment by cibernox** [comment]
@ronco I'm going one extra thing in ember-cli-head, so you might want to hold this a bit longer. We might want to release 3.0

**Comment by ronco** [comment]
@cibernox can you update the README to reflect the new compatibility requirements driven by the new `ember-cli-head` version?  Think this warrants a major version bump for this package?

**Comment by cibernox** [comment]
@ronco I think so. Will do right now.

**Pull request merged**
