### PR TITLE
Use ember-cli-head 0.4.0

### PR DESCRIPTION
**Pull request by reidab**
We ran into some pretty hairy problems with lazy-loaded engines after upgrading [ember-cli-head](https://github.com/ronco/ember-cli-head) to 0.4.0 when `ember-cli-meta-tags` was still requiring 0.3.0 and adding its `head-layout`-injecting instance-initializer.

This PR:

* Updates the `ember-cli-head` dependency to `^0.4.0`
* Drops support for Embers older than 2.10, when `-in-element` was introduced
* Switches to using `versionCompatibility` to generate `ember-try` scenarios
* Bumps the package version to `5.0.0`, since this upgrade requires manual work to add `{{head-layout}}`
* Adds a note to the README

### CODE REVIEW

**Comment by eshtadc** [comment]
Something I'm interested in as well. Please let me know if I can help.

**Comment by CvX** [comment]
I'm already using this version in a production app. Would be great if we could get these changes released!

**Comment by begedin** [comment]
👍  on getting this merged. Our other dependency, https://github.com/tim-evans/ember-page-title has updated to `ember-cli-head@0.4.0` and no longer has this issue, but this addon is preventing us from updating further.

It relates to this issue https://github.com/ronco/ember-cli-head/issues/33

**Comment by joshsmith** [comment]
Hi @ronco just wanted to check in and see if you had any plans to merge and release this?

**Comment by ronco** [comment]
Hey all,

Sorry I haven't been actively working in ember for a while now. Would
anyone like to join those project as a collaborator and take over releases?

**Comment by joshsmith** [comment]
@ronco sure, I'd be happy to help.

**Comment by begedin** [comment]
@ronco Same here

**Comment by joshsmith** [comment]
@ronco If you wanted to transfer you could do so to the @code-corps organization on GitHub, and to @joshsmith on npm. Just let me know!

**Comment by Duder-onomy** [comment]
@ronco Can we get @joshsmith and @begedin added to this project? 
I am about to make another PR for fastboot support and I cannot tell the current state of the repo as there are a bunch of legitimate pending PR's.  This is a great lib and allot of people use it. If your not using Ember anymore, can you let you birdie fly free?

**Comment by ronco** [comment]
@Duder-onomy Done.  Sorry about the radio silence.  @joshsmith @begedin You should be collaborators now.

**Comment by snewcomer** [comment]
@ronco It would be great to pickup the activity again on this repo.  I use it on a few large projects and would love to help triage issues and update the lib.  Would it be possible to add me as a collaborator?

**Comment by chriskrycho** [comment]
Plus one from me on cutting a release with these changes, @joshsmith and @begedin; and/or adding @snewcomer so they can do it. We're kind of hard-blocked on updating to Ember 2.18 (much less 3.x) by this – so if *something* doesn't get cut soon we'll have to fork it and pin to a specific hash in the forked repository until it does, which is seriously our least favorite thing ever. 😬

**Comment by reidab** [comment]
This was superseded by #71 🎉

**Comment by begedin** [comment]
@reidab Thank you for your work and apologies for the huge delay, but hopefully 5.0 will do the trick for most people. We can focus on moving this library forward now.

**Pull request closed without merging**
