### PR TITLE
Ember 2.8+ Support

### LINKED ISSUE #41: Doesn't work on ember-cli 2.8.0?
I was struggling to get it to work with my app, then decided to try on a fresh install of 2.5.1. Worked fine on that. Updated that to stock 2.8.0, and same problem.
screen shot 2016-09-18 at 1 01 48 am

### PR DESCRIPTION
**Pull request by ronco**
Removes initializer trickery implemented for Ember < 2.0 support.

Fixes #41

### CODE REVIEW

**Comment by milindalvares** [comment]
We're golden on this. Thank you @ronco you're the best! 😘

**Comment by milindalvares** [comment]
@ronco Just in case you forgot to release this into npm…

**Comment by milindalvares** [comment]
Sorry, didn't check npm, only looked at github's releases. 😬

**Comment by ronco** [comment]
@milindalvares no worries.  Second time I forgot to update github releases. 😵

**Pull request merged**
