### PR TITLE
Feature/service implementation

### PR DESCRIPTION
**Pull request by ronco**
Use a service/component implementation supporting arbitrary tag named head tags.

 - [x] service
 - [x] head-tag component
 - [x] head-tags component
 - [x] route-meta mixin compatibility
   - [x] general use case
   - [x] resetMeta
 - [x] tests
   - [x] acceptance
   - [x] unit service
   - [x] unit route meta mixin
   - [x] integration head tags
   - [x] integration head tag
 - [x] documentation

### CODE REVIEW

**Comment by ronco** [comment]
/cc @benmurden

Hey Ben,

Here's the preliminary implementation.  I've only got acceptance tests and no documentation on the new options for specifying tags.  It *should* be compatible with the legacy route-meta mixin if you're still interested in beta testing.  Deeper nested meta tags do trump parent meta tags of the same name/property.

It'll probably be a couple days till I can put more time in on this (aforementioned documentation and integration/unit tests).

Thanks!
Ron

**Comment by ronco** [comment]
Note there do seem to be some compatibility issues with Ember 2.0.

**Comment by benmurden** [comment]
@ronco Thanks for the heads up. I'll check this out and get back to you.

**Comment by benmurden** [comment]
Ahh, after trying to debug this, I just realised that my app instance doesn't have `instanceInitializer`... because it's 1.11. I'm sure if I bumped up to 1.12 it would be fine, but until then I can't test my specific integration.

**Comment by ronco** [comment]
Hey Ben,

D'oh! Yep with the current this branch as it stands now it bumps the ember
version required up to 1.12.

I think I've seen some other addons provide backwards compatibility while
using instance initializers. I'll see if I can get that working and get
back to you.

-Ron

**Comment by benmurden** [comment]
I always feel I'm slacking by not keeping up with version changes, but with the size of our application, it would almost be a full time job keeping up with how fast Ember changes!

I appreciate you keeping us legacy users in mind, though!

**Comment by ronco** [comment]
Hey Ben,

No problem. I know how it is keeping up to date (especially when you've
brought in a lot of addons). We've got one project stuck on 1.12 due to
easy forms.

**Comment by benmurden** [comment]
Can't be easy on addon authors, either!

I've had a look around for examples of supporting instance initializers and the old style at the same time, but haven't seen any yet. Do you have a link for the example you were referencing? I'd like to take a look and maybe help with the PR.

**Comment by ronco** [comment]
Hey Ben,

I actually just pushed what I think is the fix for backwards compatibility.  I found in [here](https://github.com/yahoo/ember-intl/commit/ad3c8337a5a24f103fa46f2ecc2d5a6ed34d3163).

Sorry I jumped the gun on you, I'd welcome your help on this project.

Let me know if that commit fixes things for you.

**Comment by ronco** [comment]
@benmurden 

Bummer it doesn't seem to be working on 1.11 after all.  I see the same technique in [ember-i18n](https://github.com/jamesarosen/ember-i18n/blob/master/app/initializers/ember-i18n.js). I'm not sure what the difference is.  Let me know if you have any ideas.

**Comment by benmurden** [comment]
Seems this is an issue in [ember-load-initializers](https://github.com/ember-cli/ember-load-initializers/commit/92ebad02f0cc233cca5582147b727c51a394f2e5). While this is now fixed, the latest version is, apparently, not in common use, so instance initializers can be invoked manually per [this commit on ember-perf](https://github.com/mike-north/ember-perf/commit/d846937e59612f088c7f39264d4689f2c99f6401).

**Comment by ronco** [comment]
Oh wow, interesting.  Looks like my second attempt only worked for me because I was using a real old version of ember-load-initializers.  I'll give this a try.

**Comment by ronco** [comment]
Ok, hopefully 3rd try is the charm.  I tested locally with Ember 1.11.3 and 2.0.2, both running ember-load-initializers 0.1.4.  Thanks again!

**Comment by benmurden** [comment]
Excellent! That all seems to be working without errors, now, and the bubbling is functioning as expected.

I haven't tested it with the crawlers yet, but I'm hoping all the ember component cruft doesn't confuse the social networks! I'll let you know the result of my observations.

**Comment by ronco** [comment]
@benmurden That's great!  Thanks for checking.  

I'm busy getting ready for a couple meetup talks next week, but will get this feature polished up and released after that.

**Comment by benmurden** [comment]
@ronco Sounds good. Thanks so much for taking the time to look at all these issues.

Good luck with your talks!

**Comment by ronco** [comment]
Fixes #11 #19 and #21

**Pull request merged**
