### PR TITLE
Protect against accidentally passing falsey tag definitions

### PR DESCRIPTION
**Pull request by cibernox**
On a couple apps we discovered that we had a bug that depending on server data we had no meta tags, because or array of tags contained a falsey value:

```js
headTags() {
  return [
    { /* some valid tag */ },
    { /* some valid tag */ },
    undefined,
    { /* some valid tag */ },
  ];
}
```

This is of course a bug in our app and one we should take care of, but seems that it was very simple to improve this addon so falsey tags are recognized as errors and skipped.

### CODE REVIEW

**Comment by Turbo87** [comment]
I guess the `package-lock.json` creation and `yarn.lock` change were committed unintentionally? :)

**Review by Turbo87 — APPROVED** [review]

**Comment by cibernox** [comment]
@snewcomer do you have merge rights on this repo? And publish rights on NPM?

**Review by snewcomer — APPROVED** [review]
✅🥦

**Comment by snewcomer** [comment]
I can for you!  We need to fix that test suite though.

**Pull request merged**
