### PR TITLE
Upgrade everything and octanify add-on 🏎

### PR DESCRIPTION
**Pull request by bobisjan**

### CODE REVIEW

**Comment by snewcomer** [comment]
Great and thank you!  Wonder why CI isn't running...

**Comment by bobisjan** [comment]
> This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days. Enable this workflow to resume scheduled runs.

https://github.com/ronco/ember-cli-meta-tags/actions/workflows/ci.yml

@snewcomer it looks that the workflow is disabled? 🤔

**Comment by snewcomer** [comment]
Woah.  Never knew of that feature.  Mind trying to push again?  I think I enabled the workflows again

**Comment by bobisjan** [comment]
> Mind trying to push again? I think I enabled the workflows again

Done ✅, workflow is enabled again 🥳, but approval is awaiting.

**Review by snewcomer — APPROVED** [review]
❤️

**Pull request merged**
